name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action when there is a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/checkout@v3 # Checkout repo
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1 # Setup bun
        with:
            bun-version: latest # You can also use a specific version
      - run: bun install # Only needed if you have any dependencies

      - name: Build the project
        run: bun run build # Build the project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist