name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action when there is a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/checkout@v3 # Checkout repo
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1 # Setup bun
        with:
            bun-version: latest # You can also use a specific version
      - run: bun install # Only needed if you have any dependencies

      - name: Build the project
        run: bun build  # Use Bun's build process (if needed)

      - name: Deploy to GitHub Pages
        uses: chuongmep/gh-pages-action@v2
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: public    # Folder to deploy (set to the folder containing your built website)
          token: ${{ secrets.GITHUB_TOKEN }}